apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    luckincoffee.com/cd-type: k8s
  name: k8s-gray-deploy
spec:
   steps:
    - name: deployment
      image: ubuntu
      command:
        - echo
      args:
        - "create new version deployment"
    - name: ingress
      image: ubuntu
      command:
        - echo
      args:
        - "create new version ingress"
    